### ISSUE TITLE
Is it possible to retrieve UTC time of match start?

### ISSUE THREAD

**Issue by GianniKoch** [saul/demofile-net#34]
Hi, decided to ask this via an issue.

I've been looking through the API but have not found a way to retrieve a UTC for the match start, I don't know if this is a part of the demo file though. I assumed since csstats and leetify for example do know when matches start (but this could also be because they receive the demos from Valve and in that delivery, an UTC start timestamp might get included? Don't know).
Does anyone know if there is a way to get the UTC timestamp of a match via the demo?

Thanks in advance, this parser has already helped me a lot! ❤️

**Comment by saul** [comment]
There are no timestamps in the demo file itself. Leetify etc are likely getting the timestamp from the Steam API (which contains other metadata, a link to the compressed `.dem` file).

See for example @akiver's [boiler-writter](https://github.com/akiver/boiler-writter). You can see the [`matchtime`](https://github.com/akiver/boiler-writter/blob/8eac5ab37e1e8ba87edc9aeeedeb9c7b85ed07cb/boiler-writter/protobuf/cstrike15_gcmessages.proto#L930) field here on the Steam API response. This likely represents the number of seconds since 1st Jan 1970.
